// This file is autogenerated by VESC Tool

#ifndef CONFPARSER_H_
#define CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define MAIN_CONFIG_T_SIGNATURE		723227950

// Functions
void confparser_set_defaults_main_config_t(main_config_t *conf);

// CONFPARSER_H_
#endif
