// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "main.h"
#include "confparser.h"


void confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->ble_mode = CONF_BLE_MODE;
	strcpy(conf->ble_name, CONF_BLE_NAME);
	conf->ble_pin = CONF_BLE_PIN;
}

